title: Jared Northrop
logo: "/assets/img/portrait.png"
description: |
  MS in Robotics Student at Oregon State University <br>
  BS, Computer Science, Oregon State University, 2025 <br>
  BS, Mechanical, Oregon State University, 2024 <br>
   


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

header_pages: 
- projects.md
